project_id = "zbzrmpmqijvmjbhctfoe"

[functions.send-portal-invitation]
verify_jwt = false

[functions.generate-homepage-images]
verify_jwt = false

[functions.generate-guide-content]
verify_jwt = false

[functions.get-pending-agents]
verify_jwt = false

[functions.update-portal-agent-password]
verify_jwt = false

[functions.update-portal-client-password]
verify_jwt = false
