project_id = "zbzrmpmqijvmjbhctfoe"

[functions.generate-image]
verify_jwt = false

[functions.notify-portal-message]
verify_jwt = false

[functions.send-portal-invitation]
verify_jwt = false

[functions.generate-homepage-images]
verify_jwt = false

[functions.generate-guide-content]
verify_jwt = false

[functions.get-pending-agents]
verify_jwt = false

[functions.update-portal-agent-password]
verify_jwt = false

[functions.update-portal-client-password]
verify_jwt = false

[functions.financial-analysis]
verify_jwt = false

[functions.list-contracting-managers]
verify_jwt = false

[functions.send-workshop-confirmation]
verify_jwt = false

[functions.process-workshop-reminders]
verify_jwt = false
